import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StoreProvider from '../providers/StoreProvider'
import AuthSessionProvider from '@/providers/SessionProvider'
import CartIcon from '@/components/basket/CartIcon'
import CartManager from '../components/cart/CartManager'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <AuthSessionProvider>
          <StoreProvider>
            <CartManager/>
            {children}
          </StoreProvider>
        </AuthSessionProvider>
      </body>
    </html>
  )
}